### ISSUE TITLE
Generating circos plot from block.splsda object with circosPlot returns error

### ISSUE THREAD

**Issue by tyronechen** [mixOmicsTeam/mixOmics#124] opened 2021-05-15 07:28 UTC
Please follow **all the steps** described at https://mixomics-users.discourse.group/t/reproducible-example-to-clarify-issues/470 and next fill in the items below:

------------
🐞   **Describe the bug:**

Using `circosPlot` returns the following error:
```
Error in if (pix.n < 2) { : missing value where TRUE/FALSE needed
```

------------
🔍 **reprex results from [reproducible example](https://mixomics-users.discourse.group/t/reproducible-example-to-clarify-issues/470) including sessioninfo():**

Running the below block of code will reproduce the error on the mixOmics nutrimouse dataset.

```
> packageVersion("mixOmics")
# [1] ‘6.15.48’

data(nutrimouse)
Y = nutrimouse$diet
data = list(gene = nutrimouse$gene, lipid = nutrimouse$lipid)
design = matrix(c(0,1,1,1,0,1,1,1,0), ncol = 3, nrow = 3, byrow = TRUE)
nutrimouse.sgccda <- wrapper.sgccda(X=data,
Y = Y,
design = design,
keepX = list(gene=c(10,10), lipid=c(15,15)),
ncomp = 2,
scheme = "horst")
circosPlot(nutrimouse.sgccda, cutoff = 0.7)
```
------------
🤔  **Expected behavior:**

Visualisation of the circos plot from an object of class `block.splsda`.

------------
💡  **Possible solution:**

[The specific line that threw the error appears to be line 1023 in circosPlot.R](https://github.com/mixOmicsTeam/mixOmics/blob/master/R/circosPlot.R#L1023) in `draw.arc.s` and is called by `drawIdeogram` which is called by `circosPlot`

**Comment by aljabadi** [comment] 2021-05-17 12:07
Thanks Tyrone.

Can you please include the `sessionInfo()` as well?  I have the latest R installed and using the .48 version I was unable to reproduce the behaviour (see below).
``` r
data(nutrimouse)
Y = nutrimouse$diet
data = list(gene = nutrimouse$gene, lipid = nutrimouse$lipid)
design = matrix(c(0,1,1,1,0,1,1,1,0), ncol = 3, nrow = 3, byrow = TRUE)
nutrimouse.sgccda <- wrapper.sgccda(X=data,
                                    Y = Y,
                                    design = design,
                                    keepX = list(gene=c(10,10), lipid=c(15,15)),
                                    ncomp = 2,
                                    scheme = "horst")
circosPlot(nutrimouse.sgccda, cutoff = 0.7)
```

![](https://i.imgur.com/zQkwQgx.png)

<sup>Created on 2021-05-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

<details style="margin-bottom:10px;">

<summary>Session info</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 4.0.5 (2021-03-31)
#>  os       macOS Big Sur 10.16         
#>  system   x86_64, darwin17.0          
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_AU.UTF-8                 
#>  ctype    en_AU.UTF-8                 
#>  tz       Australia/Melbourne         
#>  date     2021-05-17                  
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  !  package      * version date       lib source                
#>     assertthat     0.2.1   2019-03-21 [1] CRAN (R 4.0.2)        
#>     BiocParallel   1.24.1  2020-11-06 [1] Bioconductor          
#>     cachem         1.0.5   2021-05-15 [1] CRAN (R 4.0.5)        
#>     callr          3.7.0   2021-04-20 [1] CRAN (R 4.0.2)        
#>     cli            2.5.0   2021-04-26 [1] CRAN (R 4.0.2)        
#>     colorspace     2.0-1   2021-05-04 [1] CRAN (R 4.0.2)        
#>     corpcor        1.6.9   2017-04-01 [1] CRAN (R 4.0.2)        
#>     crayon         1.4.1   2021-02-08 [1] CRAN (R 4.0.2)        
#>     curl           4.3.1   2021-04-30 [1] CRAN (R 4.0.2)        
#>     DBI            1.1.1   2021-01-15 [1] CRAN (R 4.0.2)        
#>     desc           1.3.0   2021-03-05 [1] CRAN (R 4.0.2)        
#>     devtools       2.4.1   2021-05-05 [1] CRAN (R 4.0.2)        
#>     digest         0.6.27  2020-10-24 [1] CRAN (R 4.0.2)        
#>     dplyr          1.0.6   2021-05-05 [1] CRAN (R 4.0.2)        
#>     ellipse        0.4.2   2020-05-27 [1] CRAN (R 4.0.2)        
#>     ellipsis       0.3.2   2021-04-29 [1] CRAN (R 4.0.2)        
#>     evaluate       0.14    2019-05-28 [1] CRAN (R 4.0.1)        
#>     fansi          0.4.2   2021-01-15 [1] CRAN (R 4.0.2)        
#>     fastmap        1.1.0   2021-01-25 [1] CRAN (R 4.0.2)        
#>     fs             1.5.0   2020-07-31 [1] CRAN (R 4.0.2)        
#>     generics       0.1.0   2020-10-31 [1] CRAN (R 4.0.2)        
#>     ggplot2      * 3.3.3   2020-12-30 [1] CRAN (R 4.0.2)        
#>     ggrepel        0.9.1   2021-01-15 [1] CRAN (R 4.0.2)        
#>     glue           1.4.2   2020-08-27 [1] CRAN (R 4.0.2)        
#>     gridExtra      2.3     2017-09-09 [1] CRAN (R 4.0.2)        
#>     gtable         0.3.0   2019-03-25 [1] CRAN (R 4.0.2)        
#>     highr          0.9     2021-04-16 [1] CRAN (R 4.0.2)        
#>     htmltools      0.5.1.1 2021-01-22 [1] CRAN (R 4.0.2)        
#>     httr           1.4.2   2020-07-20 [1] CRAN (R 4.0.2)        
#>     igraph         1.2.6   2020-10-06 [1] CRAN (R 4.0.2)        
#>     knitr          1.33    2021-04-24 [1] CRAN (R 4.0.2)        
#>     lattice      * 0.20-44 2021-05-02 [1] CRAN (R 4.0.2)        
#>     lifecycle      1.0.0   2021-02-15 [1] CRAN (R 4.0.2)        
#>     magrittr       2.0.1   2020-11-17 [1] CRAN (R 4.0.2)        
#>     MASS         * 7.3-54  2021-05-03 [1] CRAN (R 4.0.2)        
#>     Matrix         1.3-3   2021-05-04 [1] CRAN (R 4.0.2)        
#>     matrixStats    0.58.0  2021-01-29 [1] CRAN (R 4.0.2)        
#>     memoise        2.0.0   2021-01-26 [1] CRAN (R 4.0.2)        
#>     mime           0.10    2021-02-13 [1] CRAN (R 4.0.2)        
#>  VP mixOmics     * 6.15.48 2021-04-14 [?] Bioconductor (R 4.0.5)
#>     munsell        0.5.0   2018-06-12 [1] CRAN (R 4.0.2)        
#>     pillar         1.6.1   2021-05-16 [1] CRAN (R 4.0.5)        
#>     pkgbuild       1.2.0   2020-12-15 [1] CRAN (R 4.0.2)        
#>     pkgconfig      2.0.3   2019-09-22 [1] CRAN (R 4.0.2)        
#>     pkgload        1.2.1   2021-04-06 [1] CRAN (R 4.0.2)        
#>     plyr           1.8.6   2020-03-03 [1] CRAN (R 4.0.2)        
#>     prettyunits    1.1.1   2020-01-24 [1] CRAN (R 4.0.2)        
#>     processx       3.5.2   2021-04-30 [1] CRAN (R 4.0.2)        
#>     ps             1.6.0   2021-02-28 [1] CRAN (R 4.0.2)        
#>     purrr          0.3.4   2020-04-17 [1] CRAN (R 4.0.2)        
#>     R6             2.5.0   2020-10-28 [1] CRAN (R 4.0.2)        
#>     rARPACK        0.11-0  2016-03-10 [1] CRAN (R 4.0.2)        
#>     RColorBrewer   1.1-2   2014-12-07 [1] CRAN (R 4.0.2)        
#>     Rcpp           1.0.6   2021-01-15 [1] CRAN (R 4.0.2)        
#>     remotes        2.3.0   2021-04-01 [1] CRAN (R 4.0.2)        
#>     reprex         2.0.0   2021-04-02 [1] CRAN (R 4.0.2)        
#>     reshape2       1.4.4   2020-04-09 [1] CRAN (R 4.0.2)        
#>     rlang          0.4.11  2021-04-30 [1] CRAN (R 4.0.2)        
#>     rmarkdown      2.8     2021-05-07 [1] CRAN (R 4.0.2)        
#>     rprojroot      2.0.2   2020-11-15 [1] CRAN (R 4.0.2)        
#>     RSpectra       0.16-0  2019-12-01 [1] CRAN (R 4.0.2)        
#>     rstudioapi     0.13    2020-11-12 [1] CRAN (R 4.0.2)        
#>     scales         1.1.1   2020-05-11 [1] CRAN (R 4.0.2)        
#>     sessioninfo    1.1.1   2018-11-05 [1] CRAN (R 4.0.2)        
#>     stringi        1.6.1   2021-05-10 [1] CRAN (R 4.0.2)        
#>     stringr        1.4.0   2019-02-10 [1] CRAN (R 4.0.2)        
#>     testthat     * 3.0.2   2021-02-14 [1] CRAN (R 4.0.2)        
#>     tibble         3.1.2   2021-05-16 [1] CRAN (R 4.0.5)        
#>     tidyr          1.1.3   2021-03-03 [1] CRAN (R 4.0.2)        
#>     tidyselect     1.1.1   2021-04-30 [1] CRAN (R 4.0.2)        
#>     usethis        2.0.1   2021-02-10 [1] CRAN (R 4.0.2)        
#>     utf8           1.2.1   2021-03-12 [1] CRAN (R 4.0.2)        
#>     vctrs          0.3.8   2021-04-29 [1] CRAN (R 4.0.2)        
#>     withr          2.4.2   2021-04-18 [1] CRAN (R 4.0.2)        
#>     xfun           0.23    2021-05-15 [1] CRAN (R 4.0.5)        
#>     xml2           1.3.2   2020-04-23 [1] CRAN (R 4.0.2)        
#>     yaml           2.2.1   2020-02-01 [1] CRAN (R 4.0.2)        
#> 
#> [1] /Library/Frameworks/R.framework/Versions/4.0/Resources/library
#> 
#>  V ── Loaded and on-disk version mismatch.
#>  P ── Loaded and on-disk path mismatch.
```

</details>

**Comment by tyronechen** [comment] 2021-05-17 12:32
Sorry, forgot to include that, here is the output of `sessionInfo()`

`R 3.6.3` on `macOS Catalina 10.15.7`

<details>
  <summary>Click to expand!</summary>
  
  ```R
  > sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS Catalina 10.15.7

Matrix products: default
BLAS/LAPACK: /Users/tche0054/miniconda3/envs/mixomics/lib/libopenblasp-r0.3.12.dylib

locale:
[1] en_AU.UTF-8/en_AU.UTF-8/en_AU.UTF-8/C/en_AU.UTF-8/en_AU.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] mixOmics_6.15.48 ggplot2_3.3.3    lattice_0.20-41  MASS_7.3-53.1

loaded via a namespace (and not attached):
 [1] ggrepel_0.9.1       Rcpp_1.0.6          tidyr_1.1.2
 [4] corpcor_1.6.9       prettyunits_1.1.1   ps_1.5.0
 [7] assertthat_0.2.1    rprojroot_2.0.2     utf8_1.1.4
[10] RSpectra_0.16-0     R6_2.5.0            plyr_1.8.6
[13] ellipse_0.4.1       pillar_1.5.0        rlang_0.4.10
[16] curl_4.3            rstudioapi_0.13     callr_3.5.1
[19] Matrix_1.3-2        desc_1.2.0          rARPACK_0.11-0
[22] devtools_2.3.2      BiocParallel_1.20.0 stringr_1.4.0
[25] igraph_1.2.5        munsell_0.5.0       compiler_3.6.3
[28] pkgconfig_2.0.3     pkgbuild_1.2.0      tidyselect_1.1.0
[31] tibble_3.0.6        gridExtra_2.3       matrixStats_0.58.0
[34] fansi_0.4.2         crayon_1.4.1        dplyr_1.0.4
[37] withr_2.4.1         grid_3.6.3          gtable_0.3.0
[40] lifecycle_1.0.0     magrittr_2.0.1      scales_1.1.1
[43] cli_2.3.1           stringi_1.5.3       cachem_1.0.4
[46] reshape2_1.4.4      fs_1.5.0            remotes_2.2.0
[49] testthat_3.0.2      ellipsis_0.3.1      generics_0.1.0
[52] vctrs_0.3.6         RColorBrewer_1.1-2  tools_3.6.3
[55] glue_1.4.2          purrr_0.3.4         processx_3.4.5
[58] pkgload_1.2.0       parallel_3.6.3      fastmap_1.1.0
[61] colorspace_2.0-0    sessioninfo_1.1.1   memoise_2.0.0
[64] usethis_2.0.1
  ```
</details>

**Comment by aljabadi** [comment] 2021-05-18 02:23
Thanks, Tyrone @tyronechen.

It seems to be caused by an odd subsetting behaviour by the dependencies. Given it does work with the latest R version I would like to assume that it is breaking lots of other legacy codes as we speak & might be fixed in the near future so that older R version users will not encounter it. I'll leave this issue open to check later on.

**Comment by tyronechen** [comment] 2021-05-18 05:58
Thanks @aljabadi , I quickly ran that on `R 4.0.3` and reproduced your plot.

**Comment by Max-Bladen** [comment] 2022-03-29 22:20
As this issue was resolved, I am closing it now. Thanks for your contribution @tyronechen

**Closed as completed by Max-Bladen** 2022-03-29 22:20 UTC
Labels: bug
