### ISSUE TITLE
Non-conformable arguments in perf()

### ISSUE THREAD

**Issue by SrikRaja** [mixOmicsTeam/mixOmics#273] opened 2022-11-24 06:50 UTC
Please follow **all the steps** described at https://mixomics-users.discourse.group/t/reproducible-example-to-clarify-issues/470 and next fill in the items below:

------------
X has 57 rows and 84 columns
Y has 57 rows and 4 columns
pls.result <- pls(X, Y, ncomp = 15, mode = "regression") #runs fine
perf.results <- perf(pls.result, validation = 'Mfold', folds = 3, progressBar = TRUE, nrepeat = 5) #errors out

Error in X.test %*% a.cv : non-conformable arguments

Issue remains even with the latest version - 6.22
------------
🔍 **reprex results from [reproducible example](https://mixomics-users.discourse.group/t/reproducible-example-to-clarify-issues/470) including sessioninfo():**

------------
🤔  **Expected behavior:**

------------
💡  **Possible solution:**

**Comment by Max-Bladen** [comment] 2022-11-27 22:20
I can see where this error is occuring ([here](https://github.com/mixOmicsTeam/mixOmics/blob/7427868e87e2c17572226f0b5c6ae319571544db/R/perf.R#L572)). However, I cannot reproduce it. My guess is that your loading vector for the X dataframe is NULL for some reason. If you provide your email, I can reach out and we can resolve this. I may need access to your data to diagnose the issue

**Comment by mfisher5** [comment] 2023-09-19 22:22
I am encountering the same problem, using the code below:

```
 > cw.lgtax.pls4 <- pls(Y = cw.lg.mat, X = index.lg.mat,  ncomp=4, mode = 'regression') ## runs
 > set.seed(33)  
 > Q2.lgtax.pls4 <- perf(cw.lgtax.pls4, validation = 'Mfold', 
                      folds = 10, nrepeat = 5)

Error in X.test %*% a.cv : non-conformable arguments
```





I'm happy to share data over email to resolve it; I attached histograms to give an overview of the data values in each matrix. The "X" matrix contains a relative abundance index based on DNA metabarcoding (COI) data, consists of 153 rows (samples) and 112 columns (taxa), the "Y" matrix contains 153 rows (samples and 1 column (continuous biological variable). 



![test_spls_histX](https://github.com/mixOmicsTeam/mixOmics/assets/22527689/1aeb7bcc-f99d-4e95-bb47-235a5c152929)
![test_spls_cw](https://github.com/mixOmicsTeam/mixOmics/assets/22527689/5f4a3e76-6ad4-498d-b2d6-b5493a459927)

**Comment by evaham1** [comment] 2024-10-18 00:35
closing here as this issue is now transferred to #298

**Closed as completed by evaham1** 2024-10-18 00:35 UTC
Labels: bug, awaiting-user
